Feature: PostgreSQL Database Configuration
  As a developer
  I want to have a properly configured PostgreSQL database
  So that I can use JPA/Hibernate for data persistence

  Background:
    Given a clean PostgreSQL 16 database instance

  Scenario: Database connection and basic configuration
    When I connect to the database
    Then the database connection should be established successfully
    And the database should be using PostgreSQL version "16"
    And the connection should use the HikariCP pool

  Scenario: JPA/Hibernate configuration
    Given JPA/Hibernate is properly configured
    When I check the JPA schema generation status
    Then JPA/Hibernate DDL should be configured
    And the database should support the required features

  Scenario: Connection pool configuration
    Given the database connection pool is configured
    When I verify the connection pool status
    Then the connection pool should be working

  Scenario: PostgreSQL optimizations
    Given PostgreSQL specific optimizations are enabled
    When I query the database metadata
    Then the database should be using PostgreSQL version "16"
    And the following database features should be available:
      | feature               | status    |
      | transactions          | supported |
      | stored procedures     | supported |
      | multiple result sets  | supported |
      | batch updates         | supported |
      | savepoints           | supported |

  Scenario: Database schema management
    Given the database schema is auto-generated by JPA/Hibernate
    When I check for required database tables
    Then JPA/Hibernate DDL should be configured
    And the database connection should be established successfully

  Scenario: Database constraints and integrity
    Given JPA/Hibernate is properly configured
    When I verify database constraints
    Then the database should support the required features
    And the connection pool should be working